name: universal_back_gesture_example
description: "Interactive example app for universal_back_gesture package"
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  universal_back_gesture:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
