name: universal_back_gesture
description: "A universal, highly customizable back gesture for any custom page transitions"
version: 2.0.0
homepage: https://github.com/TheLastFlame/universal-back-gesture
repository: https://github.com/TheLastFlame/universal-back-gesture
issue_tracker: https://github.com/TheLastFlame/universal-back-gesture/issues
license: MIT
topics:
  - back-gesture
  - navigation
  - swipe
  - transitions
  - go-router

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

